### PR TITLE
fix: allows the ability to highlight the word using the progress bar

### LINKED ISSUE #266: re-align "highlighted" word / page  focus when  moving forward / backwards without needing to "play"
Currently if the RA is "stoped"  and you click the "5 second" back button  , or move/click on the timeline   the screen will only "re-align"  to the nearest word when you click on the play button.        But  by the time the pages re-aligns  ( page transition  for example)  , the user will probably miss the first few words spoken.

It would be nice if RA would re-align  without needing to  'play' after moving the timeline.

### LINKED ISSUE #275: CI randomly fails in basic.cy.js, apparently related to scrolling
Intermittent CI workflow failure, so this is hard to reproduce. But see
https://github.com/ReadAlongs/Studio-Web/actions/runs/8903159213/job/24450409271
https://github.com/ReadAlongs/Studio-Web/actions/runs/8900297255/job/24441553848
https://github.com/ReadAlongs/Studio-Web/actions/runs/8885442422/job/24396804150

Now, the patch 
```
-    } else {
+    } else if (play_id) {
```
to `read-along.tsx` modified the error message but unfortunately did not actually make the problem go away.

### PR DESCRIPTION
**Pull request by deltork**
### PR Goal? 

- Allows the ability to highlight the words in the read-along using the progress bar, even if the audio is not currently playing
- Changes to the web-component tests to use a new state-sensitive custom command for play sequence. 

### Fixes? 
Closes #266  #275 

### Feedback sought? 
Progress bar interaction, play/stop.

### Priority? 
Low

### Tests added? 
Updates all web-components tests.

### How to test? 
Clicking various locations on the progress bar, start/pause/stop a bunch of time 

### Confidence? 
high

### Version change? 

no

### CODE REVIEW

File: packages/web-component/cypress/support/commands.js [hunk 1]
```diff
@@ -28,3 +28,7 @@ Cypress.Commands.add("readalong", () => {
 Cypress.Commands.add("readalongElement", () => {
   return cy.get("read-along").first();
 });
+
+Cypress.Commands.add("playReadAlong", () => {
+  cy.get("[data-cy=play-button]").should("be.enabled").click();
```
Comment (joanise) [inline packages/web-component/cypress/support/commands.js]: Ah, clever, this means -- I assume -- we'll wait until it's enabled before clicking it? That makes sense, so this means sometimes were were "clicking" on it before it was even enabled!

File: packages/web-component/src/components/read-along-component/read-along.tsx [hunk 2]
```diff
@@ -1706,7 +1713,11 @@ export class ReadAlongComponent {
   PlayControl = (): Element => (
     <button
       data-cy="play-button"
-      disabled={this.hasLoaded < 2}
+      disabled={
+        this.hasLoaded < 2 &&
+        this.audio_howl_sprites &&
+        this.audio_howl_sprites.sound?.duration() > 0
```
Comment (joanise) [inline packages/web-component/src/components/read-along-component/read-along.tsx]: What does `sound?.duration()` return when `sound` is undefined? Will that return value be comparable via `> 0`? I assume the intent is if sound is not defined, you want `> 0` to be false, but I just want to make sure we don't raise an exception trying to evaluate `undefined > 0` instead of just having it be fast.

Comment (joanise) [reply packages/web-component/src/components/read-along-component/read-along.tsx]: The logic here does not make sense to me, though: we're saying 

    disabled = loaded < 2 && sprites && duration > 0

isn't this backwards? I.e., shouldn't it be

    enabled = loaded >= 2 && sprites && duration > 0
    disabled = !enabled

or maybe more directly

    disabled = loaded < 2 || !sprites || !duration

and maybe even actually 

```
      disabled={
        this.hasLoaded < 2 ||
        !this.audio_howl_sprites?.sound?.duration()
      }
```

Comment (joanise) [reply packages/web-component/src/components/read-along-component/read-along.tsx]: And finally, why is the definition of `disabled` in curly braces? Why not regular round ones?
(That's not your change, it was already like that, but I don't understand it.)

File: packages/web-component/src/utils/utils.ts [hunk 3]
```diff
@@ -186,15 +186,25 @@ Sprite.prototype = {
     var seek = self.sound.seek((id = id));
     for (var j = 0; j < self._spriteLeft.length; j++) {
       // if seek passes sprite start point, replace self._reading with that sprite and slice the array of sprites left
-      if (seek * 1000 >= self._spriteLeft[j][0]) {
+      if (seek >= self._spriteLeft[j][0]) {
```
Comment (joanise) [inline packages/web-component/src/utils/utils.ts:187]: was this a ms vs s mistake all along?

**Review by joanise — CHANGES_REQUESTED** [review]
Tested, it works very well. Some comments, but most importantly a question about the semantics of the `disabled` variable.

File: packages/web-component/src/components/read-along-component/read-along.tsx (hunk 2 above)
Comment (deltork) [reply packages/web-component/src/components/read-along-component/read-along.tsx]: Created a function to walk through the states required for the successful playing of RA

File: packages/web-component/cypress/support/commands.js (hunk 1 above)
Comment (deltork) [reply packages/web-component/cypress/support/commands.js]: Yes!

File: packages/web-component/src/utils/utils.ts (hunk 3 above)
Comment (deltork) [reply packages/web-component/src/utils/utils.ts:187]: Good catch. This is a result of proper conflict resolution when rebasing. I readded the conversion to ms in the line (184) above.

**Review by deltork — COMMENTED** [review]
As discussed I have run the CI (see logs https://github.com/ReadAlongs/Studio-Web/actions/runs/9102062098/job/25055245809) 10 times and it has passed 10 times. This patch is ready.

File: packages/web-component/src/components/read-along-component/read-along.tsx [hunk 4]
```diff
@@ -443,6 +449,8 @@ export class ReadAlongComponent {
    *
    */
   play() {
+    //do not attempt to play if sprites are not initialized
+    if (this.audio_howl_sprites == undefined) return;
```
Comment (joanise) [inline packages/web-component/src/components/read-along-component/read-along.tsx]: I believe this should use `===`.

File: packages/web-component/src/components/read-along-component/read-along.tsx [hunk 5]
```diff
@@ -1187,7 +1201,24 @@ export class ReadAlongComponent {
...
+   * This could be expressed as one line
+   * but because there are multiple states involved
+   * breaking it down to make it easier to track
+   */
+  isReadyToPlay(): boolean {
+    //not ready if still audio & alignment is not loaded
+    if (this.hasLoaded < 2) return false;
 
+    //not ready if
+    if (this.audio_howl_sprites == undefined) return false;
```
Comment (joanise) [inline packages/web-component/src/components/read-along-component/read-along.tsx]: ===

File: packages/web-component/src/components/read-along-component/read-along.tsx [hunk 6]
```diff
@@ -1187,7 +1201,24 @@ export class ReadAlongComponent {
...
+
+    //not ready if
+    if (this.audio_howl_sprites.sound == undefined) return false;
```
Comment (joanise) [inline packages/web-component/src/components/read-along-component/read-along.tsx]: ===

**Review by joanise — CHANGES_REQUESTED** [review]
Now just a trivial change, my understanding is we should always test for undefined using `===` rather than `==`, otherwise I think this is ready to merge. The web-component works really nicely with these changes.

**Review by joanise — APPROVED** [review]
I made the other changes I requested, this is ready now.
Thanks for fixing this problem, I'll be happy to have stable CI back!
And the interface is nicer to use now, which is great!
